---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nuclwult/demo.lastwave.xyz/django/xyz
    - /bin/cp -R base $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R xyz $DEPLOYPATH
    - /bin/cp -R user $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
